apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cgroup-prober
  namespace: default
  labels:
    app: cgroup-prober
spec:
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 99
    type: RollingUpdate
  selector:
    matchLabels:
      app: cgroup-prober
  template:
    metadata:
      labels:
        app: cgroup-prober
    spec:
      terminationGracePeriodSeconds: 1
      tolerations:
      - operator: Exists
      containers:
      - name: cgroup-prober
        image: fl64/prober
        command: ["/entrypoint.sh"]
        volumeMounts:
          - name: prober-entrypoint
            mountPath: /entrypoint.sh
            subPath: entrypoint.sh
          - name: containerd-sock
            mountPath: /run/containerd/containerd.sock
          - name: host-proc
            mountPath: /host/proc
          - name: host-sys
            mountPath: /host/sys
      volumes:
        - name: prober-entrypoint
          configMap:
            name: prober-entrypoint
            defaultMode: 0777
        - name: containerd-sock
          hostPath:
            path: /run/containerd/containerd.sock
            type: Socket
        - name: host-proc
          hostPath:
            path: /proc
            type: Directory
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory
