---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cgroup-prober

resources:
  - ./ns.yaml
  - ./ds.yaml

configMapGenerator:
  - name: prober-entrypoint
    files:
      - entrypoint.sh=cfg/entrypoint.sh
